### ISSUE TITLE
Contracts are using WASM from target instead of target-tiny

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-examples#116]
### What version are you using?

`main`

### What did you do?

`make build`

### What did you expect to see?

https://github.com/stellar/soroban-examples/blob/cad54003976cc8869869933257647b21e60fb337/liquidity_pool/src/token_contract.rs#L16-L19 should use target-tiny.

### What did you see instead?

That line uses target instead, which means the liquidity pool contract is huge even when built for target-tiny. Liquidity pool contract is enormous (62k) as a consequence. Liquidity pool router makes the same error (147k). I'm guessing other examples make that error too.

**Comment by leighmcculloch** [comment]
There is no target-tiny anymore. If you build non-optimized, all the imports are non-optimized. If you build optimized, all the imports are optimized.

See https://github.com/stellar/soroban-examples/blob/main/Makefile#L25-L34.

Reopen if I'm misunderstanding your concern.
