### ISSUE TITLE
Rust setup issues on Gitpod Startup

### ISSUE THREAD

**Issue by Julian-dev28** [stellar/soroban-examples#250]
### What version are you using?

`soroban-examples`: 0.8.4
`soroban-SDK`: 0.8.4
`soroban-cli`: v0.7.0 (this is in the [makefile](https://github.com/stellar/soroban-examples/blob/25f2567e479b20db75ec93797dbacfd8d0a8113c/.gitpod.Dockerfile#L4-L5). Shouldn't this be v0.7.1?) 

### What did you do?

Navigate to the Gitpod demo: https://gitpod.io/#https://github.com/stellar/soroban-examples/tree/v0.8.4
Create a new Gitpod Workspace

Wait for Build to finish

### What did you expect to see?
A finished message similar to the following:

```zsh
Finished release [optimized] target(s) in 23.44s
```

### What did you see instead?

Error regarding `Cargo.toml` file
```
error: could not find `Cargo.toml` in `/workspace/soroban-examples` or any parent directory
```

Error regarding rustc Version

```zsh
error: package `soroban-sdk v0.8.4` cannot be built because it requires rustc 1.69 or newer, while the currently active rustc version is 1.68.2
Either upgrade to rustc 1.69 or newer, or use
cargo update -p soroban-sdk@0.8.4 --precise ver
where `ver` is the latest version of `soroban-sdk` supporting rustc 1.68.2
make[1]: *** [Makefile:9: build] Error 101
make[1]: Leaving directory '/workspace/soroban-examples/account'
make: *** [Makefile:9: build] Error 1
```

### Notes

Was able to successfully run `make`

After manually running the following:

```zsh
rustup self uninstall -y
rm -rf .rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

rustup update stable
rustup target add --toolchain stable wasm32-unknown-unknown
rustup component add --toolchain stable rust-src
rustup update nightly
rustup target add --toolchain nightly wasm32-unknown-unknown
rustup component add --toolchain nightly rust-src
rustup default stable

sudo apt-get update && sudo apt-get install -y binaryen
```

**Comment by leighmcculloch** [comment]
Looks like we need to change the gitpod setup to install the newer version of rust.

@Julian-dev28 What led you to installing binaryen as well?

**Comment by Julian-dev28** [comment]
@leighmcculloch I just wanted to be thorough and make sure I wasn't missing a step
