### ISSUE TITLE
Add tests to examples that run the token contract with its WASM file

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-examples#29]
### What problem does your feature solve?

Right now, tests never run the WASM. That makes it hard to know if the WASM is up to date and actually works.

### What would you like to see?

Add a feature to run with the actual WASM.

### What alternatives are there?

TODO

**Comment by leighmcculloch** [comment]
Could you expand on what you mean by run with the wasm? Do you mean run the examples as wasm? Maybe it would be a good idea if the CLI was used in a job to run them.

**Comment by jonjove** [comment]
I meant that there are examples (eg. liquidity pool) that actually deploy a token contract as part of their execution. Right now, the tests always register the native token contract instead of deploying the WASM token contract. This means the WASM for the token contract that is embedded in the liquidity pool is never actually tested, and might not work if it were actually deployed. For example, that WASM is probably quite out of date at this exact moment... maybe it works, maybe it doesn't.

This seems like a big gap in testing to me for any contract that deploys another contract. Ideally, you have a feature that selects whether to register the test contract or deploy the WASM contract. Then you can debug against the native contract, while guaranteeing that your code still works against the WASM contract.

**Comment by leighmcculloch** [comment]
Ah yes, planning to add this in August. The issue was in July but got bumped. There's not a lot of details captured here, but this is the issue: https://github.com/stellar/rs-soroban-sdk/issues/118.

I think we can close this, in answer of the question should we do this, yes.

**Comment by leighmcculloch** [comment]
@jonjove I've tried to flesh this out more here of what I think we should do, since you're thinking about this already, can you take a look and share feedback? https://github.com/stellar/rs-soroban-sdk/issues/118#issuecomment-1199499099

**Comment by jonjove** [comment]
I don't understand why this is the same as https://github.com/stellar/rs-soroban-sdk/issues/118? I see two issues with that equivalence:

1. It's already possibly to do the cross-contract calls that this requires. Doing what I described above would change the features, but _not_ any of the contract code.
2. Even if https://github.com/stellar/rs-soroban-sdk/issues/118 was required, it would still require actually adding the features.

**Comment by jonjove** [comment]
I'm not denying that things could be done to make this experience better and leverage the contract-spec for it. But it's not the same task.

**Comment by jonjove** [comment]
If you wanted to close this simply because the answer is "yes", then I will change the title to indicated that the task is to actually do it instead.

**Comment by leighmcculloch** [comment]
Apologies, I see, this task is the work to update the examples to load the token contract wasm file into the host, rather than register the test contract. Sounds great to me.

I've renamed the title to indicate the intent.

Thanks for reopening.

**Comment by jonjove** [comment]
Blocked by https://github.com/stellar/soroban-token-contract/issues/72

**Comment by jonjove** [comment]
Blocked by https://github.com/stellar/rs-soroban-sdk/issues/382

**Comment by jonjove** [comment]
Resolved by #50
