### ISSUE TITLE
Add an '__constructor(counter: Type)' example to soroban-examples

### ISSUE THREAD

**Issue by jeesunikim** [stellar/soroban-examples#339]
### What problem does your feature solve?

For the P22 upgrade, add an '__constructor(counter: Type)' example to soroban-examples. Chadoh has [an example](https://github.com/stellar/soroban-test-examples/pull/2/files).

**Comment by leighmcculloch** [comment]
+1 building on the increment example would be good. The increment example is what most of the small examples are built atop, or were at least at one point, that may have changed.

**Comment by jeesunikim** [comment]
closing this since there's a [draft pr](https://github.com/stellar/soroban-examples/pull/330/files) that adds an `__constructor(counter: Type)`
