### ISSUE TITLE
Add single offer example that uses xfer_from

### ISSUE THREAD

**Issue by sisuresh** [stellar/soroban-examples#47]
The current single offer contract follows a model where tokens need to be transferred to the contract before 'trade' is called. Both actions need to be done atomically for safety. We should demonstrate an alternative approach as well using 'approve' and 'xfer_from', which would allow the contract to send tokens between participants.

**Comment by jonjove** [comment]
I was thinking about this in the context of liquidity pool as well. This is handled in Uniswap, for example, with a router contract that is built on top of the liquidity pool. We should probably follow a similar model here because it separates core logic from "let me help you use this". Thoughts?

**Comment by sisuresh** [comment]
Are you advocating for us adding an example router contract for the existing contracts? I think that's a good idea, but the goal of this issue is a little different. I want to add a new contract that showcases a different authorization model for single offer so potential contract writers see the options available to them.

**Comment by jonjove** [comment]
Ah, I see. Both things make sense then.

**Comment by sisuresh** [comment]
Resolved by #51.
