### ISSUE TITLE
Use linear memory when creating token contract

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-examples#5]
Blocked by https://github.com/stellar/rs-stellar-contract-sdk/issues/247

**Comment by leighmcculloch** [comment]
Instead of doing that here, we should just make Binary use linear memory under the hood. It shouldn't be something, I think, that the contract has to make a cognitive decision about. If I'm misunderstanding what this issue is, can you elaborate?

**Comment by jonjove** [comment]
I 100% agree. This issue was opened before array/slice to `Binary` conversions were even available, so it was actually looping over the WASM byte-by-byte. Now that it uses the existing conversions functions, it should happen seamlessly when we do https://github.com/stellar/rs-soroban-sdk/issues/247.
