### ISSUE TITLE
Add timelock example

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-examples#72]
### What problem does your feature solve?

Access to time and ledger sequence were added in https://github.com/stellar/rs-soroban-env/pull/330 and https://github.com/stellar/rs-soroban-sdk/pull/455 but we aren't exercising this functionality at all.

### What would you like to see?

A simple timelock contract. One version of this would be analogous to a claimable balance with just one claimant and one time predicate, but I'm open to other ideas.

### What alternatives are there?

N/A

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/soroban-examples/pull/101
